import { IPhoto } from './iphoto';

export const Photos: IPhoto[] = [
  {
    id: 1,
    name: 'Fashion',
    description: '',
    imageUrl: 'fashion1.jpg',
    category: 'Fashion',
  },
  {
    id: 2,
    name: 'Fashion',
    description: '',
    imageUrl: 'fashion2.jpg',
    category: 'Fashion',
  },
  {
    id: 3,
    name: 'Fashion',
    description: '',
    imageUrl: 'fashion3.jpg',
    category: 'Fashion',
  },
  {
    id: 4,
    name: 'Fashion',
    description: '',
    imageUrl: 'fashion4.jpg',
    category: 'Fashion',
  },
  {
    id: 5,
    name: 'Fashion',
    description: '',
    imageUrl: 'fashion5.jpg',
    category: 'Fashion',
  },
  {
    id: 6,
    name: 'Nature',
    description: '',
    imageUrl: 'nature1.jpg',
    category: 'Nature',
  },
  {
    id: 7,
    name: 'Nature',
    description: '',
    imageUrl: 'nature2.jpg',
    category: 'Nature',
  },
  {
    id: 8,
    name: 'Nature',
    description: '',
    imageUrl: 'nature3.jpg',
    category: 'Nature',
  },
  {
    id: 9,
    name: 'Nature',
    description: '',
    imageUrl: 'nature4.jpg',
    category: 'Nature',
  },
  {
    id: 10,
    name: 'Nature',
    description: '',
    imageUrl: 'nature5.jpg',
    category: 'Nature',
  },
  {
    id: 11,
    name: 'Wedding',
    description: '',
    imageUrl: 'wedding1.jpg',
    category: 'Wedding',
  },
  {
    id: 12,
    name: 'Wedding',
    description: '',
    imageUrl: 'wedding2.jpg',
    category: 'Wedding',
  },
  {
    id: 13,
    name: 'Wedding',
    description: '',
    imageUrl: 'wedding3.jpg',
    category: 'Wedding',
  },
  {
    id: 14,
    name: 'Wedding',
    description: '',
    imageUrl: 'wedding4.jpg',
    category: 'Wedding',
  },
  {
    id: 15,
    name: 'Wedding',
    description: '',
    imageUrl: 'wedding5.jpg',
    category: 'Wedding',
  },
  {
    id: 16,
    name: 'Portrait',
    description: '',
    imageUrl: 'portrait1.jpg',
    category: 'Portrait',
  },
  {
    id: 17,
    name: 'Portrait',
    description: '',
    imageUrl: 'portrait2.jpg',
    category: 'Portrait',
  },
  {
    id: 18,
    name: 'Portrait',
    description: '',
    imageUrl: 'portrait3.jpg',
    category: 'Portrait',
  },
  {
    id: 19,
    name: 'Portrait',
    description: '',
    imageUrl: 'portrait4.jpg',
    category: 'Portrait',
  },
  {
    id: 20,
    name: 'Portrait',
    description: '',
    imageUrl: 'portrait5.jpg',
    category: 'Portrait',
  },
];
