import { IPhoto } from "./iphoto";


export const Photos: IPhoto[] = [
    {
    id:1,
name: "Fasion",
description: "",
imageUrl : "fasion1.jpg",
category: "fasion",
    },
     {
    id:2,
name: "Fasion",
description: "",
imageUrl : "fasion2.jpg",
category: "fasion",
    },
      {
    id:3,
name: "Fasion",
description: "",
imageUrl : "fasion3.jpg",
category: "fasion",
    },
       {
    id:4,
name: "Fasion",
description: "",
imageUrl : "fasion1.jpg",
category: "fasion",
    },
        {
    id:5,
name: "Fasion",
description: "",
imageUrl : "fasion5.jpg",
category: "fasion",
},
 {
    id:6,
name: "Nature",
description: "",
imageUrl : "nature1.jpg",
category: "nature",
    },
 {
    id:7,
name: "Nature",
description: "",
imageUrl : "nature2.jpg",
category: "nature",
    },
 {
    id:8,
name: "Nature",
description: "",
imageUrl : "nature3.jpg",
category: "nature",
    },
 {
    id:9,
name: "Nature",
description: "",
imageUrl : "nature4.jpg",
category: "nature",
    },
 {
    id:10,
name: "Nature",
description: "",
imageUrl : "nature5.jpg",
category: "nature",
    },
 {
    id:11,
name: "Wedding",
description: "",
imageUrl : "weding1.jpg",
category: "weding",
    },
  {
    id:12,
name: "Wedding",
description: "",
imageUrl : "weding2.jpg",
category: "weding",
    },
   {
    id:13,
name: "Wedding",
description: "",
imageUrl : "weding3.jpg",
category: "weding",
    },
    {
    id:14,
name: "Wedding",
description: "",
imageUrl : "weding4.jpg",
category: "weding",
    },
     {
    id:15,
name: "Wedding",
description: "",
imageUrl : "weding5.jpg",
category: "weding",
    },
     {
    id:16,
name: "Portrait",
description: "",
imageUrl : "portrait1.jpg",
category: "portrait",
    },
      {
    id:17,
name: "Portrait",
description: "",
imageUrl : "portrait2.jpg",
category: "portrait",
    },
       {
    id:18,
name: "Portrait",
description: "",
imageUrl : "portrait3.jpg",
category: "portrait",
    },
        {
    id:19,
name: "Portrait",
description: "",
imageUrl : "portrait4.jpg",
category: "portrait",
    },
         {
    id:20,
name: "Portrait",
description: "",
imageUrl : "portrait5.jpg",
category: "portrait",
},
]